name: build-site-data
on:
  schedule:
    - cron: '0 17 * * *'
jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: site
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run data
      - run: git config --global user.name 'corostats'
      - run: git config --global user.email 'corostats@users.noreply.github.com'
      - run: git add assets/stats.json
      - run: git add assets/mortality.json
      - run: git commit -m "Automated data build" || echo "No changes to commit"
      - run: git push
